### ISSUE TITLE
Logging in redirects to localhost

### ISSUE THREAD

**Issue by alan-dot-oneill** [cytomine/Cytomine-Web-UI#27]
I have followed the installation instructions for Cytomine 3.0.0 at https://doc.cytomine.org/How-to-install-Cytomine, and I selected option (b) "make your Cytomine instance accessible from other computers."  I have the URLs section of the configuration.sh file set as follows (with [my-domain] replaced with the domain name I'm using).

CORE_URL=[my-domain]
IMS_URL1=[my-domain]/ims
IMS_URL2=[my-domain]/ims2
UPLOAD_URL=[my-domain]/upload

It's not clear to me from the documentation what the user name should be, so at the log in page, I tried 'admin' and entered the password from the configs/core/cytomineconfig.groovy file.  When I click the 'Log in' button, the browser sends a POST request to http://[my-domain]/j_spring_security_check, but the response from that POST includes the following redirect header:

Location: http://localhost/login/authfail?ajax=true

Going to 'localhost' cannot work, of course, because the browser is running on one machine and the Cytomine software is running on another.

I've been looking through several of the related docker containers to see why 'localhost' is being sent instead of the domain name I selected, but thus far, no luck.

Can you offer a suggestion that might help?

Thanks much.

**Comment by alan-dot-oneill** [comment]
If anyone has any ideas, I'd be very appreciative if you'd share them with me.

**Comment by geektortoise** [comment]
Hello, 

You were right, the default username is "admin".
First of all, can you try with 4 distincts URL. Your URLs are subdomains of a common URL.
As we use nginx as a proxy, we need to have 4 distincts url : https://github.com/cytomine/Cytomine-bootstrap/blob/master/configs/nginx/nginx.conf.sample#L86
Example : 
CORE_URL=[cytomine.my-domain]
IMS_URL1=[cytomine-ims.my-domain]
IMS_URL2=[cytomine-ims2.my-domain]
UPLOAD_URL=[cytomine-upload.my-domain]

Once it is done, you can regenerate the configuration files with 
`bash init.sh`
and restart the containers (as init.sh regenerate the admin password (and it is not recognized), it's better to scratch the DB)
`sudo bash clean_docker_keep_data.sh`
sudo docker volume rm postgis_data mongodb_data`
sudo bash start_deploy.sh`

If the problem persists, can you confirm that the  grails.serverURL variable in the configs/core/cytomineconfig.groovy file is not set at localhost ?

Have a nice day

**Comment by alan-dot-oneill** [comment]
Excellent!  Thank you.  I will be able to give this a try tomorrow, and I'll be sure to respond with how it goes.

**Comment by alan-dot-oneill** [comment]
Thanks again for these tips.  (Note: Throughout this message, I've replaced my actual domain with `mydomain`.)

I changed the URLs to

`CORE_URL="cytomine.mydomain.edu"`
`IMS_URL1="cytomine-ims.mydomain.edu"`
`IMS_URL2="cytomine-ims2.mydomain.edu"`
`UPLOAD_URL="cytomine-upload.mydomain.edu"`

Then I ran `init.sh` and `clean_docker_keep_data.sh`, and I verified that `grails.serverURL` variable in the `configs/core/cytomineconfig.groovy` file has a value of `http://cytomine.mydomain.edu`.

My paths are set as follows.

`IMS_STORAGE_PATH=/mnt/cytomine/data/images`
`IMS_BUFFER_PATH=/mnt/cytomine/data/images/_buffer`
`BACKUP_PATH=/mnt/cytomine/data/backup`
`ALGO_PATH=/mnt/cytomine/data/algo/`

So to be safe, I deleted everything under `/mnt/cytomine`.

Next, I ran `start_deploy.sh`.

To test, I opened a new private window in Firefox and turned on the web developer tools.  This way, I'm least likely to get in trouble with cache.  I entered 'admin' and the generated password into the login box and clicked the Log in button, which generated a `POST` message to `http://cytomine.mydomain.edu/j_spring_security_check`.  The response to this message included the header:

`Location: http://localhost/login/authfail?ajax=true`

So the problem persists.  Out of curiosity, I looked through all of the files under `Cytomine_bootstrap` for any occurrences of `localhost` and found it in

`./Cytomine_bootstrap/configs/web_ui/nginx.conf`
`./Cytomine_bootstrap/configuration.sh`
`./Cytomine_bootstrap/utils/backup_mongo.sh`
`./Cytomine_bootstrap/utils/backup_postgis.sh`
`./Cytomine_bootstrap/utils/restore_postgis.sh`

I think the last three are not relevant to this problem, but for the first two, I see:

`cat nginx.conf | grep -i localhost`
`    server_name  localhost;`

`cat configuration.sh | grep -i localhost`
`#IIP_OFF_URL=localhost-iip-base`
`#IIP_CYTO_URL=localhost-iip-cyto`
`#IIP_JP2_URL=localhost-iip-jp2000`

Is there something else I should look into?

Thanks much.

**Comment by geektortoise** [comment]
Hello, 

Strange. :/ 
Could you add the following lines to your configs/core/cytomineconfig.groovy file (and run restart.sh)

```
grails.plugin.springsecurity.failureHandler.ajaxAuthFailUrl = "${grails.serverURL}/login/authfail?ajax=true"

log4j = {
    debug 'grails.plugin.springsecurity'
    debug 'org.springframework'
}

```

Then when trying to log in, check the logs 
`sudo docker logs -f core`

And after 
`DEBUG authentication.RequestHolderAuthenticationFilter  - Delegating to authentication failure handler grails.plugin.springsecurity.web.authentication.AjaxAwareAuthenticationFailureHandler`
check the URL in the 
DEBUG matcher.AntPathRequestMatcher  line

If it isn't working, you can send me the result of the command
` sudo docker logs core`
at the email 
info@cytomine.coop

BTW, 
What is the operating system/disto where Cytomine is running ?
